### ISSUE TITLE
Please communicate project issues in GitHub issues

### ISSUE THREAD

**Issue by MichaelKentBurns** [Samuel11s/My-first-tutorial-project#4]
Thank you for the message, but Upwork messages is not the appropriate place to communicate about your GitHub project details.   

If you have questions or issues Samuel, you should write them as Issues in your GitHub project.  That should notify Ash (and Me) about the issue.    Ash and I should respond by adding comments in your issue in GitHub.   Sending screenshots in Upwork messages is very difficult.   The GitHub project is visible to all three of us.

**Comment by Samuel11s** [comment]
Thank you @MichaelKentBurns for the guidance. I’ll make sure to use the GitHub Issues section for any questions or concerns from now on. This will help streamline our communication and keep everything organized.
