### ISSUE TITLE
Please invite Ashuza to your project. 

### ISSUE THREAD

**Issue by MichaelKentBurns** [Samuel11s/My-first-tutorial-project#5]
Read the GitHub documentation about how to invite someone to your project.  

Ashuza is your mentor.  His GitHub account is here:
https://github.com/AshDest

You need to invite him so he can see your code, see your issues and get notified when comments like this are added to your issues.

When he is invited and accepts his name should appear on the main page of your repository under contributors.

**Comment by Samuel11s** [comment]
I understand @MichaelKentBurns  I have already invited @AshDest as a contributor.
Thank you.
